# Generated by Django 5.1.2 on 2024-11-04 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='task_description',
            new_name='taskDescription',
        ),
        migrations.RemoveField(
            model_name='task',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='task',
            name='task_title',
        ),
        migrations.AddField(
            model_name='task',
            name='taskTitle',
            field=models.CharField(default='No Title', max_length=255),
            preserve_default=False,
        ),
    ]
